language: c

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - env: jobname=linux-clang
      os: linux
      compiler: clang
    - env: jobname=linux-gcc
      os: linux
      compiler: gcc
    - env: jobname=osx-clang TEST_SELECTION="t[0-4][0-9][0-9][0-9]-*.sh"
      os: osx
      osx_image: xcode10.1
      compiler: clang
    - env: jobname=osx-clang TEST_SELECTION="t[5-9][0-9][0-9][0-9]-*.sh"
      os: osx
      osx_image: xcode10.1
      compiler: clang
    - env: jobname=osx-gcc TEST_SELECTION="t[0-4][0-9][0-9][0-9]-*.sh"
      os: osx
      osx_image: xcode10.1
      compiler: gcc
    - env: jobname=osx-gcc TEST_SELECTION="t[5-9][0-9][0-9][0-9]-*.sh"
      os: osx
      osx_image: xcode10.1
      compiler: gcc
    - env: jobname=GIT_TEST_GETTEXT_POISON
      os: linux
      compiler:
      before_install:
    - env: jobname=linux-gcc-4.8
      os: linux
      dist: trusty
      compiler:
    - env: jobname=Linux32
      os: linux
      compiler:
      services:
        - docker
      script: ci/run-linux32-docker.sh
    - env: jobname=StaticAnalysis
      os: linux
      services:
        - docker
      compiler:
      script: ci/run-static-analysis.sh
      after_failure:
    - env: jobname=Documentation
      os: linux
      compiler:
      script: ci/test-documentation.sh
      after_failure:

before_install: ci/install-dependencies.sh
script: ci/run-build-and-tests.sh
after_failure: ci/print-test-failures.sh

notifications:
  email: false
